osx_image: xcode10.1
language: swift
script:
  - xcodebuild -scheme NewsAPI-Example -workspace Example/NewsAPI.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.1' build test
  
# - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/NewsAPI.xcworkspace -scheme NewsAPI-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint
